<?php
/**
 * MikhMon Agent System - Universal Installer
 * Combines Database Configuration, System Check, and Module Installation
 * 
 * @version 3.1 (Modern UI)
 * @date 2025-12-05
 */

// Security: Allow access, but recommend deletion after use
$security_warning = "PENTING: Hapus file ini setelah instalasi selesai!";

error_reporting(E_ALL);
ini_set('display_errors', 1);
set_time_limit(600);

// Path to config file
$configFile = __DIR__ . '/include/db_config.php';
$configExists = file_exists($configFile);

// Handle Database Config Save
$configMessage = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['save_config'])) {
    $host = $_POST['db_host'] ?? 'localhost';
    $user = $_POST['db_user'] ?? 'root';
    $pass = $_POST['db_pass'] ?? '';
    $name = $_POST['db_name'] ?? 'mikhmon_agent';
    
    // Test connection
    try {
        $dsn = "mysql:host=$host;charset=utf8mb4";
        $pdo = new PDO($dsn, $user, $pass, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
        
        // Create database if not exists
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        
        // Generate config file content
        $configContent = "<?php
/*
 * Database Configuration for Agent System
 * Generated by Universal Installer
 */

// Database credentials
define('DB_HOST', '$host');
define('DB_USER', '$user');
define('DB_PASS', '$pass');
define('DB_NAME', '$name');
define('DB_CHARSET', 'utf8mb4');

// Create database connection
function getDBConnection() {
    static $conn = null;
    
    if ($conn === null) {
        try {
            $dsn = \"mysql:host=\" . DB_HOST . \";dbname=\" . DB_NAME . \";charset=\" . DB_CHARSET;
            $options = [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
                PDO::ATTR_EMULATE_PREPARES => false,
            ];
            $conn = new PDO($dsn, DB_USER, DB_PASS, $options);
        } catch (PDOException $e) {
            error_log(\"Database connection failed: \" . \$e->getMessage());
            return false;
        }
    }
    
    return $conn;
}
?>";
        
        // Write config file
        if (file_put_contents($configFile, $configContent)) {
            $configMessage = '<div class="alert alert-success"><i class="fas fa-check-circle"></i> Konfigurasi database berhasil disimpan! Mengalihkan...</div>';
            $configExists = true;
            // Refresh to load new config
            echo "<script>setTimeout(function(){ window.location.href = '?step=check'; }, 1500);</script>";
        } else {
            $configMessage = '<div class="alert alert-danger"><i class="fas fa-times-circle"></i> Gagal menulis file include/db_config.php. Cek permission folder.</div>';
        }
        
    } catch (PDOException $e) {
        $configMessage = '<div class="alert alert-danger"><i class="fas fa-exclamation-triangle"></i> Gagal koneksi database: ' . $e->getMessage() . '</div>';
    }
}

// Try to connect if config exists
$pdo = null;
$dbConnected = false;
if ($configExists) {
    require_once $configFile;
    if (function_exists('getDBConnection')) {
        $pdo = getDBConnection();
        if ($pdo) {
            $dbConnected = true;
        }
    }
}

// Helper Functions
function logMessage($message, $type = 'info') {
    $icon = ['success' => '✅', 'error' => '❌', 'warning' => '⚠️', 'info' => 'ℹ️'][$type] ?? 'ℹ️';
    echo "<div class='log-entry log-$type'>$icon $message</div>";
    flush();
}

function tableExists($pdo, $table) {
    try {
        $stmt = $pdo->query("SHOW TABLES LIKE '$table'");
        return $stmt->rowCount() > 0;
    } catch (Exception $e) { return false; }
}

function columnExists($pdo, $table, $column) {
    try {
        $stmt = $pdo->query("SHOW COLUMNS FROM `$table` LIKE '$column'");
        return $stmt->rowCount() > 0;
    } catch (Exception $e) { return false; }
}

function indexExists($pdo, $table, $index) {
    try {
        $stmt = $pdo->query("SHOW INDEX FROM `$table` WHERE Key_name = '$index'");
        return $stmt->rowCount() > 0;
    } catch (Exception $e) { return false; }
}

function ensureTable($pdo, $name, $ddl) {
    if (!tableExists($pdo, $name)) {
        logMessage("Membuat tabel $name ...", 'info');
        $pdo->exec($ddl);
        logMessage("Tabel $name berhasil dibuat", 'success');
    } else {
        logMessage("Tabel $name sudah ada", 'info');
    }
}

function ensureColumn($pdo, $table, $column, $definition, $after = null) {
    if (!columnExists($pdo, $table, $column)) {
        $afterSql = $after ? " AFTER `$after`" : '';
        $pdo->exec("ALTER TABLE `$table` ADD COLUMN `$column` $definition$afterSql");
        logMessage("Kolom $table.$column ditambahkan", 'success');
    }
}

function ensureIndex($pdo, $table, $index, $definition) {
    if (!indexExists($pdo, $table, $index)) {
        $pdo->exec("ALTER TABLE `$table` ADD $definition");
        logMessage("Index $index ditambahkan ke $table", 'success');
    }
}

function ensureAgent($pdo, $code, $name, $status = 'active') {
    $stmt = $pdo->prepare("SELECT id FROM agents WHERE agent_code = ?");
    $stmt->execute([$code]);
    $id = $stmt->fetchColumn();
    
    if ($id) {
        return $id;
    }
    
    $stmt = $pdo->prepare("INSERT INTO agents (agent_code, agent_name, status, phone) VALUES (?, ?, ?, ?)");
    $stmt->execute([$code, $name, $status, 'seed-'.strtolower($code)]);
    return $pdo->lastInsertId();
}

?>
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MikhMon Agent Installer</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        :root {
            --primary: #4f46e5;
            --primary-hover: #4338ca;
            --success: #10b981;
            --danger: #ef4444;
            --warning: #f59e0b;
            --bg: #f3f4f6;
            --card-bg: #ffffff;
            --text: #1f2937;
            --text-light: #6b7280;
            --border: #e5e7eb;
        }
        
        * { box-sizing: border-box; margin: 0; padding: 0; }
        
        body {
            font-family: 'Inter', sans-serif;
            background-color: var(--bg);
            color: var(--text);
            line-height: 1.5;
            min-height: 100vh;
            display: flex;
            flex-direction: column;
            align-items: center;
            padding: 40px 20px;
        }
        
        .container {
            width: 100%;
            max-width: 850px;
            background: var(--card-bg);
            border-radius: 16px;
            box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1);
            overflow: hidden;
        }
        
        .header {
            background: linear-gradient(135deg, var(--primary) 0%, #6366f1 100%);
            color: white;
            padding: 40px;
            text-align: center;
            position: relative;
        }
        
        .header h1 {
            font-size: 28px;
            font-weight: 700;
            margin-bottom: 8px;
            letter-spacing: -0.5px;
        }
        
        .header p {
            font-size: 16px;
            opacity: 0.9;
            font-weight: 300;
        }
        
        .content {
            padding: 40px;
        }
        
        /* Step Wizard */
        .step-wizard {
            display: flex;
            justify-content: space-between;
            margin-bottom: 40px;
            position: relative;
        }
        
        .step-wizard::before {
            content: '';
            position: absolute;
            top: 15px;
            left: 0;
            right: 0;
            height: 2px;
            background: var(--border);
            z-index: 0;
        }
        
        .step-item {
            position: relative;
            z-index: 1;
            text-align: center;
            width: 33.33%;
        }
        
        .step-circle {
            width: 32px;
            height: 32px;
            background: var(--bg);
            border: 2px solid var(--border);
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            margin: 0 auto 10px;
            font-weight: 600;
            color: var(--text-light);
            transition: all 0.3s ease;
        }
        
        .step-label {
            font-size: 14px;
            font-weight: 500;
            color: var(--text-light);
        }
        
        .step-item.active .step-circle {
            background: var(--primary);
            border-color: var(--primary);
            color: white;
            box-shadow: 0 0 0 4px rgba(79, 70, 229, 0.2);
        }
        
        .step-item.active .step-label {
            color: var(--primary);
            font-weight: 600;
        }
        
        .step-item.completed .step-circle {
            background: var(--success);
            border-color: var(--success);
            color: white;
        }
        
        /* Forms */
        .form-group {
            margin-bottom: 24px;
        }
        
        .form-group label {
            display: block;
            margin-bottom: 8px;
            font-weight: 500;
            color: var(--text);
            font-size: 14px;
        }
        
        .form-control {
            width: 100%;
            padding: 12px 16px;
            border: 1px solid var(--border);
            border-radius: 8px;
            font-size: 15px;
            transition: border-color 0.2s, box-shadow 0.2s;
            font-family: inherit;
        }
        
        .form-control:focus {
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 3px rgba(79, 70, 229, 0.1);
        }
        
        /* Buttons */
        .btn {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            padding: 12px 24px;
            border-radius: 8px;
            border: none;
            font-weight: 600;
            cursor: pointer;
            text-decoration: none;
            font-size: 15px;
            transition: all 0.2s;
            gap: 8px;
        }
        
        .btn-primary {
            background-color: var(--primary);
            color: white;
        }
        
        .btn-primary:hover {
            background-color: var(--primary-hover);
            transform: translateY(-1px);
        }
        
        .btn-success {
            background-color: var(--success);
            color: white;
        }
        
        .btn-success:hover {
            background-color: #059669;
            transform: translateY(-1px);
        }
        
        .btn-warning {
            background-color: var(--warning);
            color: white;
        }
        
        .btn-block {
            width: 100%;
        }
        
        /* Alerts */
        .alert {
            padding: 16px;
            border-radius: 8px;
            margin-bottom: 24px;
            display: flex;
            align-items: flex-start;
            gap: 12px;
            font-size: 14px;
        }
        
        .alert i {
            font-size: 18px;
            margin-top: 2px;
        }
        
        .alert-success { background-color: #ecfdf5; color: #065f46; border: 1px solid #a7f3d0; }
        .alert-danger { background-color: #fef2f2; color: #991b1b; border: 1px solid #fecaca; }
        .alert-warning { background-color: #fffbeb; color: #92400e; border: 1px solid #fde68a; }
        
        /* Tables */
        .status-table {
            width: 100%;
            border-collapse: separate;
            border-spacing: 0;
            border: 1px solid var(--border);
            border-radius: 8px;
            overflow: hidden;
            margin-bottom: 24px;
        }
        
        .status-table th, .status-table td {
            padding: 12px 16px;
            text-align: left;
            border-bottom: 1px solid var(--border);
        }
        
        .status-table th {
            background-color: #f9fafb;
            font-weight: 600;
            font-size: 13px;
            text-transform: uppercase;
            letter-spacing: 0.5px;
            color: var(--text-light);
        }
        
        .status-table tr:last-child td {
            border-bottom: none;
        }
        
        .status-badge {
            display: inline-flex;
            align-items: center;
            padding: 4px 10px;
            border-radius: 9999px;
            font-size: 12px;
            font-weight: 600;
            gap: 6px;
        }
        
        .badge-success { background-color: #d1fae5; color: #065f46; }
        .badge-danger { background-color: #fee2e2; color: #991b1b; }
        
        /* Log Area */
        .log-area {
            background-color: #111827;
            color: #10b981;
            padding: 20px;
            border-radius: 8px;
            font-family: 'Consolas', 'Monaco', monospace;
            font-size: 13px;
            max-height: 400px;
            overflow-y: auto;
            margin-top: 20px;
            border: 1px solid #374151;
        }
        
        .log-entry {
            margin: 4px 0;
            padding-left: 12px;
            border-left: 2px solid transparent;
        }
        
        .log-success { border-left-color: var(--success); }
        .log-error { border-left-color: var(--danger); color: #f87171; }
        .log-info { border-left-color: #3b82f6; color: #60a5fa; }
        
        /* Animations */
        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(10px); }
            to { opacity: 1; transform: translateY(0); }
        }
        
        .fade-in {
            animation: fadeIn 0.4s ease-out forwards;
        }
    </style>
</head>
<body>

<div class="container fade-in">
    <div class="header">
        <h1><i class="fas fa-rocket"></i> MikhMon Agent Installer</h1>
        <p>All-in-One Setup: Database Config & Module Installation</p>
    </div>

    <div class="content">
        <?php if ($security_warning): ?>
            <div class="alert alert-warning">
                <i class="fas fa-exclamation-triangle"></i>
                <div><strong>Keamanan:</strong> <?= $security_warning ?></div>
            </div>
        <?php endif; ?>

        <?php
        $step = $_GET['step'] ?? ($dbConnected ? 'check' : 'config');
        ?>

        <!-- Step Wizard -->
        <div class="step-wizard">
            <div class="step-item <?= $step == 'config' ? 'active' : ($dbConnected ? 'completed' : '') ?>">
                <div class="step-circle"><?= $dbConnected ? '<i class="fas fa-check"></i>' : '1' ?></div>
                <div class="step-label">Database</div>
            </div>
            <div class="step-item <?= $step == 'check' ? 'active' : ($step == 'install' ? 'completed' : '') ?>">
                <div class="step-circle"><?= $step == 'install' ? '<i class="fas fa-check"></i>' : '2' ?></div>
                <div class="step-label">System Check</div>
            </div>
            <div class="step-item <?= $step == 'install' ? 'active' : '' ?>">
                <div class="step-circle">3</div>
                <div class="step-label">Installation</div>
            </div>
        </div>

        <!-- STEP 1: CONFIGURATION -->
        <?php if ($step == 'config'): ?>
            <div class="fade-in">
                <h2 style="margin-bottom: 20px; font-size: 20px;">⚙️ Konfigurasi Database</h2>
                <?= $configMessage ?>
                
                <?php if ($dbConnected): ?>
                    <div class="alert alert-success">
                        <i class="fas fa-check-circle"></i>
                        <div>
                            <strong>Terhubung!</strong><br>
                            Database <strong><?= DB_NAME ?></strong> di <strong><?= DB_HOST ?></strong> siap digunakan.
                        </div>
                    </div>
                    <a href="?step=check" class="btn btn-success btn-block">
                        Lanjut ke System Check <i class="fas fa-arrow-right"></i>
                    </a>
                <?php else: ?>
                    <form method="POST">
                        <div class="form-group">
                            <label>Database Host</label>
                            <input type="text" name="db_host" class="form-control" value="<?= defined('DB_HOST') ? DB_HOST : 'localhost' ?>" required placeholder="e.g. localhost">
                        </div>
                        <div class="form-group">
                            <label>Database Username</label>
                            <input type="text" name="db_user" class="form-control" value="<?= defined('DB_USER') ? DB_USER : 'root' ?>" required placeholder="e.g. root">
                        </div>
                        <div class="form-group">
                            <label>Database Password</label>
                            <input type="password" name="db_pass" class="form-control" value="<?= defined('DB_PASS') ? DB_PASS : '' ?>" placeholder="Password database">
                        </div>
                        <div class="form-group">
                            <label>Database Name</label>
                            <input type="text" name="db_name" class="form-control" value="<?= defined('DB_NAME') ? DB_NAME : 'mikhmon_agent' ?>" required placeholder="e.g. mikhmon_agent">
                            <small style="color: var(--text-light); margin-top: 4px; display: block; font-size: 12px;">
                                <i class="fas fa-info-circle"></i> Database akan otomatis dibuat jika belum ada.
                            </small>
                        </div>
                        <button type="submit" name="save_config" class="btn btn-primary btn-block">
                            <i class="fas fa-save"></i> Simpan & Test Koneksi
                        </button>
                    </form>
                <?php endif; ?>
            </div>
        
        <!-- STEP 2: SYSTEM CHECK -->
        <?php elseif ($step == 'check'): ?>
            <div class="fade-in">
                <?php if (!$dbConnected): ?>
                    <div class="alert alert-danger">
                        <i class="fas fa-times-circle"></i>
                        <div>Database belum terkoneksi. <a href="?step=config" style="color: inherit; font-weight: bold;">Kembali ke Config</a></div>
                    </div>
                <?php else: ?>
                    <h2 style="margin-bottom: 20px; font-size: 20px;">📊 Status Sistem</h2>
                    
                    <table class="status-table">
                        <thead>
                            <tr>
                                <th>Nama Tabel</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                        <?php
                        $tables = [
                            'agents', 'agent_settings', 'agent_prices', 'agent_transactions', 
                            'agent_vouchers', 'agent_commissions', 'agent_billing_payments',
                            'payment_gateway_config', 'agent_profile_pricing', 'public_sales', 'payment_methods',
                            'billing_profiles', 'billing_customers', 'billing_invoices', 'billing_payments',
                            'billing_settings', 'billing_logs', 'billing_portal_otps',
                            'digiflazz_products', 'digiflazz_transactions', 'voucher_settings', 'site_pages'
                        ];
                        
                        $missingCount = 0;
                        foreach ($tables as $table) {
                            $exists = tableExists($pdo, $table);
                            if (!$exists) $missingCount++;
                            $status = $exists 
                                ? '<span class="status-badge badge-success"><i class="fas fa-check"></i> Installed</span>' 
                                : '<span class="status-badge badge-danger"><i class="fas fa-times"></i> Missing</span>';
                            echo "<tr><td><code>$table</code></td><td>$status</td></tr>";
                        }
                        ?>
                        </tbody>
                    </table>

                    <div style="text-align: center; margin-top: 30px;">
                        <?php if ($missingCount > 0): ?>
                            <div class="alert alert-warning">
                                <i class="fas fa-exclamation-triangle"></i>
                                <div>Ditemukan <strong><?= $missingCount ?></strong> tabel yang belum terinstall atau hilang.</div>
                            </div>
                            <a href="?step=install" class="btn btn-primary btn-block" style="font-size: 16px; padding: 15px;">
                                <i class="fas fa-rocket"></i> Install Semua Modul
                            </a>
                        <?php else: ?>
                            <div class="alert alert-success">
                                <i class="fas fa-check-circle"></i>
                                <div>Semua tabel sistem sudah terinstall dengan benar.</div>
                            </div>
                            <a href="?step=install" class="btn btn-warning btn-block">
                                <i class="fas fa-sync-alt"></i> Re-Install / Perbaiki Database
                            </a>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
            </div>

        <!-- STEP 3: INSTALLATION -->
        <?php elseif ($step == 'install'): ?>
            <div class="fade-in">
                <?php if (!$dbConnected): ?>
                    <div class="alert alert-danger">
                        <i class="fas fa-times-circle"></i>
                        <div>Database belum terkoneksi.</div>
                    </div>
                <?php else: ?>
                    <h2 style="margin-bottom: 20px; font-size: 20px;">🚀 Proses Instalasi</h2>
                    <div class="log-area">
                        <?php
                        // --- START INSTALLATION LOGIC (From fix_all_modules.php) ---
                        
                        logMessage('Memulai proses instalasi...', 'info');
                        
                        // 1. Define Tables
                        $tables = [
                            'agents' => "CREATE TABLE `agents` (
                                `id` INT AUTO_INCREMENT PRIMARY KEY,
                                `agent_code` VARCHAR(20) NOT NULL,
                                `agent_name` VARCHAR(100) NOT NULL,
                                `email` VARCHAR(100),
                                `phone` VARCHAR(20),
                                `password` VARCHAR(255),
                                `address` TEXT,
                                `balance` DECIMAL(15,2) DEFAULT 0.00,
                                `commission_rate` DECIMAL(5,2) DEFAULT 0.00,
                                `status` ENUM('active','inactive','suspended') DEFAULT 'active',
                                `level` ENUM('bronze','silver','gold','platinum') DEFAULT 'bronze',
                                `created_by` VARCHAR(50),
                                `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                `last_login` TIMESTAMP NULL,
                                `notes` TEXT,
                                UNIQUE KEY `unique_agent_code` (`agent_code`),
                                KEY `idx_agent_code` (`agent_code`),
                                KEY `idx_status` (`status`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'agent_settings' => "CREATE TABLE `agent_settings` (
                                `id` INT AUTO_INCREMENT PRIMARY KEY,
                                `agent_id` INT NOT NULL,
                                `setting_key` VARCHAR(100) NOT NULL,
                                `setting_value` TEXT,
                                `setting_type` VARCHAR(20),
                                `description` TEXT,
                                `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                `updated_by` VARCHAR(50),
                                CONSTRAINT `fk_agent_settings_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`) ON DELETE CASCADE,
                                UNIQUE KEY `unique_agent_setting` (`agent_id`, `setting_key`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'agent_prices' => "CREATE TABLE `agent_prices` (
                                `id` INT AUTO_INCREMENT PRIMARY KEY,
                                `agent_id` INT NOT NULL,
                                `profile_name` VARCHAR(100) NOT NULL,
                                `buy_price` DECIMAL(15,2) NOT NULL,
                                `sell_price` DECIMAL(15,2) NOT NULL,
                                `stock_limit` INT,
                                `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                CONSTRAINT `fk_agent_prices_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`) ON DELETE CASCADE,
                                UNIQUE KEY `unique_agent_profile` (`agent_id`, `profile_name`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'agent_transactions' => "CREATE TABLE `agent_transactions` (
                                `id` INT AUTO_INCREMENT PRIMARY KEY,
                                `agent_id` INT NOT NULL,
                                `transaction_type` ENUM('topup','generate','refund','commission','penalty') NOT NULL,
                                `amount` DECIMAL(15,2) NOT NULL,
                                `balance_before` DECIMAL(15,2) NOT NULL,
                                `balance_after` DECIMAL(15,2) NOT NULL,
                                `profile_name` VARCHAR(100),
                                `voucher_username` VARCHAR(100),
                                `voucher_password` VARCHAR(100),
                                `quantity` INT,
                                `description` TEXT,
                                `reference_id` VARCHAR(50),
                                `created_by` VARCHAR(50),
                                `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                `ip_address` VARCHAR(45),
                                `user_agent` TEXT,
                                CONSTRAINT `fk_agent_transactions_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`) ON DELETE CASCADE,
                                INDEX `idx_agent_date` (`agent_id`, `created_at`),
                                INDEX `idx_reference` (`reference_id`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'agent_vouchers' => "CREATE TABLE `agent_vouchers` (
                                `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                                `agent_id` INT NOT NULL,
                                `transaction_id` INT DEFAULT NULL,
                                `username` VARCHAR(100) NOT NULL,
                                `password` VARCHAR(100) NOT NULL,
                                `profile_name` VARCHAR(100) NOT NULL,
                                `buy_price` DECIMAL(15,2) NOT NULL,
                                `sell_price` DECIMAL(15,2) DEFAULT NULL,
                                `status` ENUM('active','used','expired','deleted') DEFAULT 'active',
                                `customer_phone` VARCHAR(20) DEFAULT NULL,
                                `customer_name` VARCHAR(100) DEFAULT NULL,
                                `sent_via` ENUM('web','whatsapp','manual') DEFAULT 'web',
                                `sent_at` TIMESTAMP NULL DEFAULT NULL,
                                `used_at` TIMESTAMP NULL DEFAULT NULL,
                                `expired_at` TIMESTAMP NULL DEFAULT NULL,
                                `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                `notes` TEXT DEFAULT NULL,
                                CONSTRAINT `fk_agent_vouchers_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`) ON DELETE CASCADE,
                                INDEX `idx_agent_id` (`agent_id`),
                                INDEX `idx_transaction_id` (`transaction_id`),
                                INDEX `idx_username` (`username`),
                                INDEX `idx_status` (`status`),
                                INDEX `idx_customer_phone` (`customer_phone`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'agent_commissions' => "CREATE TABLE `agent_commissions` (
                                `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                                `agent_id` INT NOT NULL,
                                `voucher_id` INT UNSIGNED DEFAULT NULL,
                                `commission_amount` DECIMAL(15,2) NOT NULL,
                                `commission_percent` DECIMAL(5,2) NOT NULL,
                                `voucher_price` DECIMAL(15,2) NOT NULL,
                                `status` ENUM('pending','paid','cancelled') DEFAULT 'pending',
                                `earned_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
                                `paid_at` TIMESTAMP NULL DEFAULT NULL,
                                `notes` TEXT DEFAULT NULL,
                                CONSTRAINT `fk_agent_commissions_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`) ON DELETE CASCADE,
                                INDEX `idx_agent_id` (`agent_id`),
                                INDEX `idx_status` (`status`),
                                INDEX `idx_voucher_id` (`voucher_id`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'agent_billing_payments' => "CREATE TABLE `agent_billing_payments` (
                                `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                                `agent_id` INT NOT NULL,
                                `invoice_id` BIGINT UNSIGNED NOT NULL,
                                `amount` DECIMAL(15,2) NOT NULL,
                                `fee` DECIMAL(15,2) DEFAULT 0.00,
                                `status` ENUM('paid','refunded') DEFAULT 'paid',
                                `processed_by` VARCHAR(50) DEFAULT 'system',
                                `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                CONSTRAINT `fk_agent_billing_payments_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`) ON DELETE CASCADE,
                                INDEX `idx_agent_id` (`agent_id`),
                                INDEX `idx_invoice_id` (`invoice_id`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'payment_gateway_config' => "CREATE TABLE `payment_gateway_config` (
                                `id` INT AUTO_INCREMENT PRIMARY KEY,
                                `gateway_name` VARCHAR(50) NOT NULL,
                                `is_active` TINYINT(1) DEFAULT 0,
                                `is_sandbox` TINYINT(1) DEFAULT 1,
                                `api_key` VARCHAR(255),
                                `api_secret` VARCHAR(255),
                                `merchant_code` VARCHAR(100),
                                `callback_token` VARCHAR(255),
                                `config_json` TEXT,
                                `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                UNIQUE KEY `unique_gateway` (`gateway_name`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'agent_profile_pricing' => "CREATE TABLE `agent_profile_pricing` (
                                `id` INT AUTO_INCREMENT PRIMARY KEY,
                                `agent_id` INT NOT NULL,
                                `profile_name` VARCHAR(100) NOT NULL,
                                `display_name` VARCHAR(100) NOT NULL,
                                `description` TEXT,
                                `price` DECIMAL(10,2) NOT NULL,
                                `original_price` DECIMAL(10,2),
                                `is_active` TINYINT(1) DEFAULT 1,
                                `is_featured` TINYINT(1) DEFAULT 0,
                                `icon` VARCHAR(50) DEFAULT 'fa-wifi',
                                `color` VARCHAR(20) DEFAULT 'blue',
                                `sort_order` INT DEFAULT 0,
                                `user_type` ENUM('voucher','member') DEFAULT 'voucher',
                                `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                CONSTRAINT `fk_agent_profile_pricing_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`) ON DELETE CASCADE,
                                UNIQUE KEY `unique_agent_profile` (`agent_id`, `profile_name`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'public_sales' => "CREATE TABLE `public_sales` (
                                `id` INT AUTO_INCREMENT PRIMARY KEY,
                                `transaction_id` VARCHAR(100) NOT NULL,
                                `payment_reference` VARCHAR(100),
                                `agent_id` INT NOT NULL DEFAULT 1,
                                `profile_id` INT NOT NULL DEFAULT 1,
                                `customer_name` VARCHAR(100) NOT NULL DEFAULT '',
                                `customer_phone` VARCHAR(20) NOT NULL DEFAULT '',
                                `customer_email` VARCHAR(100),
                                `profile_name` VARCHAR(100) NOT NULL DEFAULT '',
                                `price` DECIMAL(10,2) NOT NULL DEFAULT 0,
                                `admin_fee` DECIMAL(10,2) DEFAULT 0,
                                `total_amount` DECIMAL(10,2) NOT NULL DEFAULT 0,
                                `gateway_name` VARCHAR(50) NOT NULL DEFAULT '',
                                `payment_method` VARCHAR(50),
                                `payment_channel` VARCHAR(50),
                                `payment_url` TEXT,
                                `qr_url` TEXT,
                                `virtual_account` VARCHAR(50),
                                `payment_instructions` TEXT,
                                `expired_at` DATETIME,
                                `paid_at` DATETIME,
                                `status` VARCHAR(20) DEFAULT 'pending',
                                `voucher_code` VARCHAR(50),
                                `voucher_password` VARCHAR(50),
                                `voucher_generated_at` DATETIME,
                                `voucher_sent_at` DATETIME,
                                `ip_address` VARCHAR(50),
                                `user_agent` TEXT,
                                `callback_data` TEXT,
                                `notes` TEXT,
                                `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                CONSTRAINT `fk_public_sales_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`) ON DELETE CASCADE,
                                CONSTRAINT `fk_public_sales_profile` FOREIGN KEY (`profile_id`) REFERENCES `agent_profile_pricing`(`id`) ON DELETE CASCADE,
                                UNIQUE KEY `unique_transaction` (`transaction_id`),
                                INDEX `idx_payment_reference` (`payment_reference`),
                                INDEX `idx_status` (`status`),
                                INDEX `idx_customer_phone` (`customer_phone`),
                                INDEX `idx_created_at` (`created_at`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'payment_methods' => "CREATE TABLE `payment_methods` (
                                `id` INT AUTO_INCREMENT PRIMARY KEY,
                                `gateway_name` VARCHAR(50) NOT NULL,
                                `method_code` VARCHAR(50) NOT NULL,
                                `method_name` VARCHAR(100) NOT NULL,
                                `method_type` VARCHAR(20) NOT NULL,
                                `name` VARCHAR(100) NOT NULL DEFAULT '',
                                `type` VARCHAR(50) NOT NULL DEFAULT '',
                                `display_name` VARCHAR(100) NOT NULL DEFAULT '',
                                `icon` VARCHAR(100),
                                `icon_url` VARCHAR(255),
                                `admin_fee_type` ENUM('percentage','fixed','flat','percent') DEFAULT 'fixed',
                                `admin_fee_value` DECIMAL(10,2) DEFAULT 0,
                                `min_amount` DECIMAL(10,2) DEFAULT 0,
                                `max_amount` DECIMAL(12,2) DEFAULT 999999999.99,
                                `is_active` TINYINT(1) DEFAULT 1,
                                `sort_order` INT DEFAULT 0,
                                `config` TEXT,
                                `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                UNIQUE KEY `unique_gateway_method` (`gateway_name`, `method_code`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'voucher_settings' => "CREATE TABLE `voucher_settings` (
                                `id` INT AUTO_INCREMENT PRIMARY KEY,
                                `setting_key` VARCHAR(100) UNIQUE NOT NULL,
                                `setting_value` TEXT,
                                `description` TEXT,
                                `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'site_pages' => "CREATE TABLE `site_pages` (
                                `id` INT AUTO_INCREMENT PRIMARY KEY,
                                `page_slug` VARCHAR(50) UNIQUE NOT NULL,
                                `page_title` VARCHAR(200) NOT NULL,
                                `page_content` TEXT NOT NULL,
                                `is_active` TINYINT(1) DEFAULT 1,
                                `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'billing_portal_otps' => "CREATE TABLE `billing_portal_otps` (
                                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                `customer_id` INT UNSIGNED NOT NULL,
                                `identifier` VARCHAR(191) NOT NULL,
                                `otp_code` VARCHAR(191) NOT NULL,
                                `expires_at` DATETIME NOT NULL,
                                `attempts` TINYINT UNSIGNED NOT NULL DEFAULT 0,
                                `max_attempts` TINYINT UNSIGNED NOT NULL DEFAULT 5,
                                `sent_via` ENUM('whatsapp','sms','email') DEFAULT 'whatsapp',
                                `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                PRIMARY KEY (`id`),
                                KEY `idx_customer_identifier` (`customer_id`, `identifier`),
                                KEY `idx_expires_at` (`expires_at`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'digiflazz_products' => "CREATE TABLE `digiflazz_products` (
                                `id` INT AUTO_INCREMENT PRIMARY KEY,
                                `buyer_sku_code` VARCHAR(50) NOT NULL,
                                `product_name` VARCHAR(150) NOT NULL,
                                `brand` VARCHAR(100) DEFAULT NULL,
                                `category` VARCHAR(50) DEFAULT NULL,
                                `type` ENUM('prepaid','postpaid') DEFAULT 'prepaid',
                                `price` INT NOT NULL,
                                `buyer_price` INT DEFAULT NULL,
                                `seller_price` INT DEFAULT NULL,
                                `status` ENUM('active','inactive') DEFAULT 'active',
                                `desc_header` VARCHAR(150) DEFAULT NULL,
                                `desc_footer` TEXT DEFAULT NULL,
                                `icon_url` VARCHAR(255) DEFAULT NULL,
                                `allow_markup` TINYINT(1) DEFAULT 1,
                                `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                UNIQUE KEY `unique_buyer_sku` (`buyer_sku_code`),
                                INDEX `idx_brand` (`brand`),
                                INDEX `idx_category` (`category`),
                                INDEX `idx_status` (`status`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'digiflazz_transactions' => "CREATE TABLE `digiflazz_transactions` (
                                `id` INT AUTO_INCREMENT PRIMARY KEY,
                                `agent_id` INT,
                                `ref_id` VARCHAR(60) NOT NULL,
                                `buyer_sku_code` VARCHAR(50) NOT NULL,
                                `customer_no` VARCHAR(50) NOT NULL,
                                `customer_name` VARCHAR(100),
                                `status` ENUM('pending','success','failed','refund') DEFAULT 'pending',
                                `message` VARCHAR(255),
                                `price` INT DEFAULT 0,
                                `sell_price` INT DEFAULT 0,
                                `serial_number` VARCHAR(100),
                                `response` TEXT,
                                `whatsapp_notified` TINYINT(1) NOT NULL DEFAULT 0,
                                `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                CONSTRAINT `fk_digiflazz_transactions_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`) ON DELETE SET NULL,
                                INDEX `idx_ref` (`ref_id`),
                                INDEX `idx_agent` (`agent_id`),
                                INDEX `idx_status` (`status`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'billing_profiles' => "CREATE TABLE `billing_profiles` (
                                `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                `profile_name` VARCHAR(100) NOT NULL,
                                `price_monthly` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
                                `speed_label` VARCHAR(100) DEFAULT NULL,
                                `mikrotik_profile_normal` VARCHAR(100) NOT NULL,
                                `mikrotik_profile_isolation` VARCHAR(100) NOT NULL,
                                `description` TEXT DEFAULT NULL,
                                `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
                                PRIMARY KEY (`id`),
                                UNIQUE KEY `uniq_profile_name` (`profile_name`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'billing_customers' => "CREATE TABLE `billing_customers` (
                                `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
                                `profile_id` INT UNSIGNED NOT NULL,
                                `name` VARCHAR(150) NOT NULL,
                                `phone` VARCHAR(32) DEFAULT NULL,
                                `email` VARCHAR(150) DEFAULT NULL,
                                `address` TEXT DEFAULT NULL,
                                `service_number` VARCHAR(100) DEFAULT NULL,
                                `billing_day` TINYINT UNSIGNED NOT NULL DEFAULT 1,
                                `status` ENUM('active','inactive') NOT NULL DEFAULT 'active',
                                `is_isolated` TINYINT(1) NOT NULL DEFAULT 0,
                                `next_isolation_date` DATE DEFAULT NULL,
                                `auto_isolation` TINYINT(1) NOT NULL DEFAULT 1,
                                `genieacs_match_mode` ENUM('device_id','phone_tag','pppoe_username') NOT NULL DEFAULT 'device_id',
                                `genieacs_pppoe_username` VARCHAR(191) DEFAULT NULL,
                                `notes` TEXT DEFAULT NULL,
                                `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
                                PRIMARY KEY (`id`),
                                KEY `idx_profile_id` (`profile_id`),
                                KEY `idx_billing_day` (`billing_day`),
                                CONSTRAINT `fk_billing_customers_profile` FOREIGN KEY (`profile_id`) REFERENCES `billing_profiles`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'billing_invoices' => "CREATE TABLE `billing_invoices` (
                                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                `customer_id` INT UNSIGNED NOT NULL,
                                `profile_snapshot` JSON DEFAULT NULL,
                                `period` CHAR(7) NOT NULL,
                                `due_date` DATE NOT NULL,
                                `amount` DECIMAL(12,2) NOT NULL DEFAULT 0.00,
                                `status` ENUM('draft','unpaid','paid','overdue','cancelled') NOT NULL DEFAULT 'unpaid',
                                `paid_at` DATETIME DEFAULT NULL,
                                `payment_channel` VARCHAR(100) DEFAULT NULL,
                                `reference_number` VARCHAR(100) DEFAULT NULL,
                                `paid_via` VARCHAR(50) DEFAULT NULL,
                                `paid_via_agent_id` INT UNSIGNED DEFAULT NULL,
                                `whatsapp_sent_at` DATETIME DEFAULT NULL,
                                `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
                                PRIMARY KEY (`id`),
                                UNIQUE KEY `uniq_customer_period` (`customer_id`,`period`),
                                KEY `idx_status` (`status`),
                                CONSTRAINT `fk_billing_invoices_customer` FOREIGN KEY (`customer_id`) REFERENCES `billing_customers`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'billing_settings' => "CREATE TABLE `billing_settings` (
                                `setting_key` VARCHAR(100) NOT NULL,
                                `setting_value` TEXT DEFAULT NULL,
                                `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                                PRIMARY KEY (`setting_key`)
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'billing_logs' => "CREATE TABLE `billing_logs` (
                                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                `invoice_id` BIGINT UNSIGNED DEFAULT NULL,
                                `customer_id` INT UNSIGNED DEFAULT NULL,
                                `event` VARCHAR(100) NOT NULL,
                                `metadata` JSON DEFAULT NULL,
                                `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                PRIMARY KEY (`id`),
                                KEY `idx_invoice_id` (`invoice_id`),
                                KEY `idx_customer_id` (`customer_id`),
                                CONSTRAINT `fk_billing_logs_invoice` FOREIGN KEY (`invoice_id`) REFERENCES `billing_invoices`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
                                CONSTRAINT `fk_billing_logs_customer` FOREIGN KEY (`customer_id`) REFERENCES `billing_customers`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
                            
                            'billing_payments' => "CREATE TABLE `billing_payments` (
                                `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                                `invoice_id` BIGINT UNSIGNED NOT NULL,
                                `amount` DECIMAL(12,2) NOT NULL,
                                `payment_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                `method` VARCHAR(100) DEFAULT NULL,
                                `notes` TEXT DEFAULT NULL,
                                `created_by` INT UNSIGNED DEFAULT NULL,
                                `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                PRIMARY KEY (`id`),
                                KEY `idx_invoice_id` (`invoice_id`),
                                CONSTRAINT `fk_billing_payments_invoice` FOREIGN KEY (`invoice_id`) REFERENCES `billing_invoices`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
                            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
                        ];
                        
                        foreach ($tables as $name => $ddl) {
                            ensureTable($pdo, $name, $ddl);
                        }
                        
                        // === TELEGRAM INTEGRATION TABLES ===
                        logMessage('Installing Telegram integration tables...', 'info');
                        
                        // Telegram Settings Table
                        $telegramSettingsTable = "CREATE TABLE `telegram_settings` (
                            `id` INT AUTO_INCREMENT PRIMARY KEY,
                            `setting_key` VARCHAR(100) NOT NULL UNIQUE,
                            `setting_value` TEXT,
                            `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
                        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
                        ensureTable($pdo, 'telegram_settings', $telegramSettingsTable);
                        
                        // Telegram Webhook Log Table
                        $telegramWebhookLogTable = "CREATE TABLE `telegram_webhook_log` (
                            `id` INT AUTO_INCREMENT PRIMARY KEY,
                            `chat_id` VARCHAR(50) NOT NULL,
                            `username` VARCHAR(100),
                            `first_name` VARCHAR(100),
                            `last_name` VARCHAR(100),
                            `message` TEXT,
                            `command` VARCHAR(50),
                            `response` TEXT,
                            `status` ENUM('success', 'error') DEFAULT 'success',
                            `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            INDEX `idx_chat_id` (`chat_id`),
                            INDEX `idx_created_at` (`created_at`)
                        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
                        ensureTable($pdo, 'telegram_webhook_log', $telegramWebhookLogTable);
                        
                        // Telegram User Mapping Table
                        $telegramUserMappingTable = "CREATE TABLE `telegram_user_mapping` (
                            `id` INT AUTO_INCREMENT PRIMARY KEY,
                            `phone` VARCHAR(20) NOT NULL,
                            `telegram_chat_id` VARCHAR(50) NOT NULL,
                            `telegram_username` VARCHAR(100),
                            `first_name` VARCHAR(100),
                            `last_name` VARCHAR(100),
                            `is_verified` TINYINT(1) DEFAULT 0,
                            `verification_code` VARCHAR(10),
                            `verification_expires` DATETIME,
                            `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                            UNIQUE KEY `unique_phone` (`phone`),
                            UNIQUE KEY `unique_chat_id` (`telegram_chat_id`),
                            INDEX `idx_phone` (`phone`),
                            INDEX `idx_chat_id` (`telegram_chat_id`)
                        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci";
                        ensureTable($pdo, 'telegram_user_mapping', $telegramUserMappingTable);
                        
                        // Add Telegram columns to agents table
                        ensureColumn($pdo, 'agents', 'telegram_chat_id', 'VARCHAR(50) NULL', 'phone');
                        ensureColumn($pdo, 'agents', 'telegram_username', 'VARCHAR(100) NULL', 'telegram_chat_id');
                        ensureColumn($pdo, 'agents', 'preferred_channel', "ENUM('whatsapp', 'telegram', 'both') DEFAULT 'whatsapp'", 'telegram_username');
                        ensureIndex($pdo, 'agents', 'idx_telegram_chat_id', "INDEX `idx_telegram_chat_id` (`telegram_chat_id`)");
                        
                        // Add Telegram column to billing_customers table
                        if (tableExists($pdo, 'billing_customers')) {
                            ensureColumn($pdo, 'billing_customers', 'telegram_chat_id', 'VARCHAR(50) NULL', 'phone');
                            ensureIndex($pdo, 'billing_customers', 'idx_telegram_chat_id', "INDEX `idx_telegram_chat_id` (`telegram_chat_id`)");
                        }
                        
                        // Insert default Telegram settings
                        try {
                            $stmt = $pdo->prepare("INSERT IGNORE INTO `telegram_settings` (`setting_key`, `setting_value`) VALUES (?, ?)");
                            $defaultTelegramSettings = [
                                ['telegram_enabled', '0'],
                                ['telegram_bot_token', ''],
                                ['telegram_webhook_mode', '1'],
                                ['telegram_admin_chat_ids', ''],
                                ['telegram_welcome_message', '🤖 *Selamat datang di Bot MikhMon*\n\nKetik /help untuk melihat perintah yang tersedia.']
                            ];
                            
                            foreach ($defaultTelegramSettings as $setting) {
                                $stmt->execute($setting);
                            }
                            logMessage('Default Telegram settings inserted', 'success');
                        } catch (Exception $e) {
                            logMessage('Error inserting Telegram settings: ' . $e->getMessage(), 'error');
                        }
                        
                        logMessage('Telegram integration installed successfully!', 'success');
                        
                        // 2. Ensure Columns

                        ensureColumn($pdo, 'agent_profile_pricing', 'sort_order', 'INT DEFAULT 0', 'color');
                        ensureColumn($pdo, 'agent_profile_pricing', 'user_type', "ENUM('voucher','member') DEFAULT 'voucher'", 'sort_order');
                        ensureColumn($pdo, 'payment_methods', 'icon_url', 'VARCHAR(255) DEFAULT NULL', 'icon');
                        ensureColumn($pdo, 'payment_methods', 'config', 'TEXT', 'sort_order');
                        
                        if (!columnExists($pdo, 'agent_settings', 'agent_id')) {
                            $pdo->exec("ALTER TABLE `agent_settings` ADD COLUMN `agent_id` INT NOT NULL DEFAULT 1 AFTER `id`");
                            $pdo->exec("ALTER TABLE `agent_settings` ADD CONSTRAINT `fk_agent_settings_agent` FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`) ON DELETE CASCADE");
                            logMessage('Kolom agent_settings.agent_id ditambahkan', 'success');
                        }
                        
                        ensureColumn($pdo, 'agent_settings', 'setting_type', "VARCHAR(20) DEFAULT 'string'", 'setting_value');
                        ensureColumn($pdo, 'agent_settings', 'description', 'TEXT', 'setting_type');
                        ensureColumn($pdo, 'agent_settings', 'updated_by', 'VARCHAR(50)', 'updated_at');
                        
                        ensureIndex($pdo, 'agent_settings', 'idx_agent_id', "INDEX `idx_agent_id` (`agent_id`)");
                        
                        // 3. Seed Data
                        logMessage('Seeding default data...', 'info');
                        
                        $agentDemoId = ensureAgent($pdo, 'AG001', 'Agent Demo');
                        $agentTesterId = ensureAgent($pdo, 'AG5136', 'tester');
                        $agentPublicId = ensureAgent($pdo, 'PUBLIC', 'Public Catalog');
                        
                        // Default Settings (Including WhatsApp API)
                        $defaultAgentSettings = [
                            ['agent_id' => $agentDemoId, 'key' => 'admin_whatsapp_numbers', 'value' => '6281234567890'],
                            ['agent_id' => $agentDemoId, 'key' => 'agent_can_set_sell_price', 'value' => '1'],
                            ['agent_id' => $agentDemoId, 'key' => 'agent_registration_enabled', 'value' => '1'],
                            ['agent_id' => $agentDemoId, 'key' => 'min_topup_amount', 'value' => '50000'],
                            ['agent_id' => $agentDemoId, 'key' => 'max_topup_amount', 'value' => '10000000'],
                            ['agent_id' => $agentDemoId, 'key' => 'commission_enabled', 'value' => '1'],
                            ['agent_id' => $agentDemoId, 'key' => 'default_commission_percent', 'value' => '5'],
                            ['agent_id' => $agentDemoId, 'key' => 'whatsapp_notification_enabled', 'value' => '1'],
                            ['agent_id' => $agentDemoId, 'key' => 'voucher_prefix_agent', 'value' => 'AG'],
                            ['agent_id' => $agentDemoId, 'key' => 'whatsapp_gateway_url', 'value' => 'https://api.whatsapp.com'],
                            ['agent_id' => $agentDemoId, 'key' => 'whatsapp_token', 'value' => ''],
                            // WhatsApp API settings for VoucherGenerator (PUBLIC VOUCHER)
                            ['agent_id' => $agentDemoId, 'key' => 'whatsapp_api_url', 'value' => 'https://api.fonnte.com/send', 'type' => 'string', 'description' => 'WhatsApp API Gateway URL for public voucher delivery'],
                            ['agent_id' => $agentDemoId, 'key' => 'whatsapp_api_key', 'value' => '', 'type' => 'string', 'description' => 'WhatsApp API Key/Token - MUST BE CONFIGURED!'],
                            // Digiflazz settings
                            ['agent_id' => $agentDemoId, 'key' => 'digiflazz_enabled', 'value' => '0'],
                            ['agent_id' => $agentDemoId, 'key' => 'digiflazz_username', 'value' => ''],
                            ['agent_id' => $agentDemoId, 'key' => 'digiflazz_api_key', 'value' => ''],
                            ['agent_id' => $agentDemoId, 'key' => 'digiflazz_is_production', 'value' => '0'],
                            ['agent_id' => $agentDemoId, 'key' => 'default_markup_nominal', 'value' => '300'],
                            // Voucher settings
                            ['agent_id' => $agentDemoId, 'key' => 'voucher_username_password_same', 'value' => '0', 'type' => 'boolean', 'description' => 'Username dan password sama atau berbeda'],
                            ['agent_id' => $agentDemoId, 'key' => 'voucher_username_type', 'value' => 'alphanumeric', 'type' => 'string', 'description' => 'Tipe karakter username: numeric, alpha, alphanumeric'],
                            ['agent_id' => $agentDemoId, 'key' => 'voucher_username_length', 'value' => '8', 'type' => 'number', 'description' => 'Panjang karakter username'],
                            ['agent_id' => $agentDemoId, 'key' => 'voucher_password_type', 'value' => 'alphanumeric', 'type' => 'string', 'description' => 'Tipe karakter password: numeric, alpha, alphanumeric'],
                            ['agent_id' => $agentDemoId, 'key' => 'voucher_password_length', 'value' => '6', 'type' => 'number', 'description' => 'Panjang karakter password'],
                            ['agent_id' => $agentDemoId, 'key' => 'voucher_prefix_enabled', 'value' => '1', 'type' => 'boolean', 'description' => 'Gunakan prefix untuk username'],
                            ['agent_id' => $agentDemoId, 'key' => 'voucher_prefix', 'value' => 'AG', 'type' => 'string', 'description' => 'Prefix untuk username'],
                            ['agent_id' => $agentDemoId, 'key' => 'voucher_uppercase', 'value' => '1', 'type' => 'boolean', 'description' => 'Gunakan huruf kapital'],
                            // Payment information
                            ['agent_id' => $agentDemoId, 'key' => 'payment_bank_name', 'value' => 'BCA', 'type' => 'string', 'description' => 'Nama Bank'],
                            ['agent_id' => $agentDemoId, 'key' => 'payment_account_number', 'value' => '1234567890', 'type' => 'string', 'description' => 'Nomor Rekening'],
                            ['agent_id' => $agentDemoId, 'key' => 'payment_account_name', 'value' => 'Nama Pemilik', 'type' => 'string', 'description' => 'Nama Pemilik Rekening'],
                            ['agent_id' => $agentDemoId, 'key' => 'payment_wa_confirm', 'value' => '08123456789', 'type' => 'string', 'description' => 'Nomor WhatsApp Konfirmasi'],
                        ];
                        
                        $settingStmt = $pdo->prepare("INSERT INTO agent_settings (agent_id, setting_key, setting_value, setting_type, description) VALUES (:agent, :key, :value, :type, :description)
                            ON DUPLICATE KEY UPDATE setting_value = VALUES(setting_value), setting_type = VALUES(setting_type), description = VALUES(description)");
                        foreach ($defaultAgentSettings as $row) {
                            $settingStmt->execute([
                                ':agent' => $row['agent_id'],
                                ':key' => $row['key'],
                                ':value' => $row['value'],
                                ':type' => $row['type'] ?? 'string',
                                ':description' => $row['description'] ?? ''
                            ]);
                        }
                        logMessage('Agent settings updated', 'success');
                        
                        // Payment Methods
                        $tripayMethods = [
                            ['tripay', 'QRIS', 'QRIS (Semua Bank & E-Wallet)', 'qris', 'QRIS', 'qris', 'QRIS (Semua Bank & E-Wallet)', 'fa-qrcode', 'percentage', 0, 10000, 5000000, 1, 1],
                            ['tripay', 'BRIVA', 'BRI Virtual Account', 'va', 'BRIVA', 'va', 'BRI Virtual Account', 'fa-bank', 'fixed', 4000, 10000, 5000000, 1, 2],
                            ['tripay', 'BNIVA', 'BNI Virtual Account', 'va', 'BNIVA', 'va', 'BNI Virtual Account', 'fa-bank', 'fixed', 4000, 10000, 5000000, 1, 3],
                            ['tripay', 'BCAVA', 'BCA Virtual Account', 'va', 'BCAVA', 'va', 'BCA Virtual Account', 'fa-bank', 'fixed', 4000, 10000, 5000000, 1, 4],
                            ['tripay', 'MANDIRIVA', 'Mandiri Virtual Account', 'va', 'MANDIRIVA', 'va', 'Mandiri Virtual Account', 'fa-bank', 'fixed', 4000, 10000, 5000000, 1, 5],
                            ['tripay', 'PERMATAVA', 'Permata Virtual Account', 'va', 'PERMATAVA', 'va', 'Permata Virtual Account', 'fa-bank', 'fixed', 4000, 10000, 5000000, 1, 6],
                            ['tripay', 'OVO', 'OVO', 'ewallet', 'OVO', 'ewallet', 'OVO', 'fa-mobile', 'percentage', 2.5, 10000, 2000000, 1, 7],
                            ['tripay', 'DANA', 'DANA', 'ewallet', 'DANA', 'ewallet', 'DANA', 'fa-mobile', 'percentage', 2.5, 10000, 2000000, 1, 8],
                            ['tripay', 'SHOPEEPAY', 'ShopeePay', 'ewallet', 'SHOPEEPAY', 'ewallet', 'ShopeePay', 'fa-mobile', 'percentage', 2.5, 10000, 2000000, 1, 9],
                            ['tripay', 'LINKAJA', 'LinkAja', 'ewallet', 'LINKAJA', 'ewallet', 'LinkAja', 'fa-mobile', 'percentage', 2.5, 10000, 2000000, 1, 10],
                            ['tripay', 'ALFAMART', 'Alfamart', 'retail', 'ALFAMART', 'retail', 'Alfamart', 'fa-shopping-cart', 'fixed', 5000, 10000, 5000000, 1, 11],
                            ['tripay', 'INDOMARET', 'Indomaret', 'retail', 'INDOMARET', 'retail', 'Indomaret', 'fa-shopping-cart', 'fixed', 5000, 10000, 5000000, 1, 12],
                        ];
                        $methodStmt = $pdo->prepare("INSERT INTO payment_methods
                            (gateway_name, method_code, method_name, method_type, name, type, display_name, icon, admin_fee_type, admin_fee_value, min_amount, max_amount, is_active, sort_order)
                            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                            ON DUPLICATE KEY UPDATE method_name = VALUES(method_name), method_type = VALUES(method_type),
                                name = VALUES(name), type = VALUES(type), display_name = VALUES(display_name), icon = VALUES(icon),
                                admin_fee_type = VALUES(admin_fee_type), admin_fee_value = VALUES(admin_fee_value),
                                min_amount = VALUES(min_amount), max_amount = VALUES(max_amount), is_active = VALUES(is_active),
                                sort_order = VALUES(sort_order)");
                        foreach ($tripayMethods as $method) {
                            $methodStmt->execute($method);
                        }
                        logMessage('Payment methods updated', 'success');
                        
                        // Pages
                        $pdo->exec("INSERT IGNORE INTO site_pages (page_slug, page_title, page_content) VALUES
                            ('tos', 'Syarat dan Ketentuan', '<h3>Syarat dan Ketentuan</h3><p>Sesuaikan konten ini.</p>'),
                            ('privacy', 'Kebijakan Privasi', '<h3>Kebijakan Privasi</h3><p>Sesuaikan konten ini.</p>'),
                            ('faq', 'FAQ', '<h3>FAQ</h3><p>Sesuaikan konten ini.</p>')");
                        logMessage('Default pages created', 'success');
                        
                        logMessage('✅ INSTALASI SELESAI!', 'success');
                        ?>
                    </div>

                    <!-- Quick Access Links -->
                    <div style="margin-top: 30px; text-align: left;">
                        <h3 style="font-size: 18px; margin-bottom: 15px; color: var(--text); border-bottom: 1px solid var(--border); padding-bottom: 10px;">
                            <i class="fas fa-link"></i> Akses Cepat Aplikasi
                        </h3>
                        <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 15px;">
                            <!-- Agent Dashboard -->
                            <a href="agent/" target="_blank" style="text-decoration: none; color: inherit;">
                                <div style="background: #fff; padding: 20px; border-radius: 12px; border: 1px solid var(--border); transition: all 0.2s; box-shadow: 0 2px 4px rgba(0,0,0,0.05);" onmouseover="this.style.borderColor='var(--primary)';this.style.transform='translateY(-2px)'" onmouseout="this.style.borderColor='var(--border)';this.style.transform='translateY(0)'">
                                    <div style="font-weight: 700; color: var(--primary); margin-bottom: 8px; font-size: 16px;">
                                        <i class="fas fa-user-tie"></i> Agent Dashboard
                                    </div>
                                    <div style="font-size: 13px; color: var(--text-light); line-height: 1.4;">
                                        Login area untuk Reseller / Agen Topup & Voucher.
                                    </div>
                                    <div style="margin-top: 10px; font-size: 12px; color: var(--primary); font-weight: 600;">
                                        Buka Link <i class="fas fa-external-link-alt"></i>
                                    </div>
                                </div>
                            </a>

                            <!-- Public Sales -->
                            <a href="public/index.php?agent=AG001" target="_blank" style="text-decoration: none; color: inherit;">
                                <div style="background: #fff; padding: 20px; border-radius: 12px; border: 1px solid var(--border); transition: all 0.2s; box-shadow: 0 2px 4px rgba(0,0,0,0.05);" onmouseover="this.style.borderColor='var(--success)';this.style.transform='translateY(-2px)'" onmouseout="this.style.borderColor='var(--border)';this.style.transform='translateY(0)'">
                                    <div style="font-weight: 700; color: var(--success); margin-bottom: 8px; font-size: 16px;">
                                        <i class="fas fa-shopping-cart"></i> Penjualan Online
                                    </div>
                                    <div style="font-size: 13px; color: var(--text-light); line-height: 1.4;">
                                        Halaman katalog & pembelian voucher untuk user public.
                                    </div>
                                    <div style="margin-top: 10px; font-size: 12px; color: var(--success); font-weight: 600;">
                                        Buka Link <i class="fas fa-external-link-alt"></i>
                                    </div>
                                </div>
                            </a>

                            <!-- Billing Portal -->
                            <a href="public/billing_login.php" target="_blank" style="text-decoration: none; color: inherit;">
                                <div style="background: #fff; padding: 20px; border-radius: 12px; border: 1px solid var(--border); transition: all 0.2s; box-shadow: 0 2px 4px rgba(0,0,0,0.05);" onmouseover="this.style.borderColor='var(--warning)';this.style.transform='translateY(-2px)'" onmouseout="this.style.borderColor='var(--border)';this.style.transform='translateY(0)'">
                                    <div style="font-weight: 700; color: var(--warning); margin-bottom: 8px; font-size: 16px;">
                                        <i class="fas fa-file-invoice-dollar"></i> Portal Pelanggan
                                    </div>
                                    <div style="font-size: 13px; color: var(--text-light); line-height: 1.4;">
                                        Login area pelanggan bulanan (Cek Tagihan & Bayar).
                                    </div>
                                    <div style="margin-top: 10px; font-size: 12px; color: var(--warning); font-weight: 600;">
                                        Buka Link <i class="fas fa-external-link-alt"></i>
                                    </div>
                                </div>
                            </a>
                            
                            <!-- Telegram Settings -->
                            <a href="settings/telegram_settings.php" target="_blank" style="text-decoration: none; color: inherit;">
                                <div style="background: #fff; padding: 20px; border-radius: 12px; border: 1px solid var(--border); transition: all 0.2s; box-shadow: 0 2px 4px rgba(0,0,0,0.05);" onmouseover="this.style.borderColor='#0088cc';this.style.transform='translateY(-2px)'" onmouseout="this.style.borderColor='var(--border)';this.style.transform='translateY(0)'">
                                    <div style="font-weight: 700; color: #0088cc; margin-bottom: 8px; font-size: 16px;">
                                        <i class="fab fa-telegram"></i> Telegram Settings
                                    </div>
                                    <div style="font-size: 13px; color: var(--text-light); line-height: 1.4;">
                                        Konfigurasi Telegram Bot & Webhook Management.
                                    </div>
                                    <div style="margin-top: 10px; font-size: 12px; color: #0088cc; font-weight: 600;">
                                        Buka Link <i class="fas fa-external-link-alt"></i>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    
                    <!-- Telegram Bot Setup (Optional) -->
                    <div style="margin-top: 30px;">
                        <h3 style="font-size: 18px; margin-bottom: 15px; color: var(--text); border-bottom: 1px solid var(--border); padding-bottom: 10px;">
                            <i class="fab fa-telegram"></i> Setup Telegram Bot (Opsional)
                        </h3>
                        
                        <?php
                        // Handle Telegram setup form submission
                        if (isset($_POST['save_telegram_config'])) {
                            try {
                                $telegramEnabled = isset($_POST['telegram_enabled']) ? '1' : '0';
                                $telegramBotToken = trim($_POST['telegram_bot_token']);
                                $telegramWebhookMode = isset($_POST['telegram_webhook_mode']) ? '1' : '0';
                                $telegramAdminChatIds = trim($_POST['telegram_admin_chat_ids']);
                                
                                // Update database settings
                                $stmt = $pdo->prepare("INSERT INTO telegram_settings (setting_key, setting_value) VALUES (?, ?) ON DUPLICATE KEY UPDATE setting_value = ?");
                                $stmt->execute(['telegram_enabled', $telegramEnabled, $telegramEnabled]);
                                $stmt->execute(['telegram_bot_token', $telegramBotToken, $telegramBotToken]);
                                $stmt->execute(['telegram_webhook_mode', $telegramWebhookMode, $telegramWebhookMode]);
                                $stmt->execute(['telegram_admin_chat_ids', $telegramAdminChatIds, $telegramAdminChatIds]);
                                
                                // Update config file
                                $configFile = 'include/telegram_config.php';
                                if (file_exists($configFile)) {
                                    $configContent = file_get_contents($configFile);
                                    
                                    // Update bot token
                                    $configContent = preg_replace(
                                        "/define\('TELEGRAM_BOT_TOKEN', '.*?'\);/",
                                        "define('TELEGRAM_BOT_TOKEN', '$telegramBotToken');",
                                        $configContent
                                    );
                                    
                                    // Update enabled status
                                    $enabledValue = $telegramEnabled == '1' ? 'true' : 'false';
                                    $configContent = preg_replace(
                                        "/define\('TELEGRAM_ENABLED', .*?\);/",
                                        "define('TELEGRAM_ENABLED', $enabledValue);",
                                        $configContent
                                    );
                                    
                                    // Update webhook mode
                                    $webhookValue = $telegramWebhookMode == '1' ? 'true' : 'false';
                                    $configContent = preg_replace(
                                        "/define\('TELEGRAM_WEBHOOK_MODE', .*?\);/",
                                        "define('TELEGRAM_WEBHOOK_MODE', $webhookValue);",
                                        $configContent
                                    );
                                    
                                    file_put_contents($configFile, $configContent);
                                }
                                
                                logMessage('✅ Telegram bot configured successfully!', 'success');
                                echo '<div class="alert alert-success" style="margin-bottom: 20px;">
                                    <i class="fas fa-check-circle"></i>
                                    <div><strong>Telegram Bot Configured!</strong><br>
                                    Bot token dan settings telah disimpan. Anda bisa test bot di Telegram sekarang.</div>
                                </div>';
                            } catch (Exception $e) {
                                logMessage('Error configuring Telegram: ' . $e->getMessage(), 'error');
                                echo '<div class="alert alert-danger" style="margin-bottom: 20px;">
                                    <i class="fas fa-exclamation-circle"></i>
                                    <div>Error: ' . htmlspecialchars($e->getMessage()) . '</div>
                                </div>';
                            }
                        }
                        ?>
                        
                        <div style="background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 12px; padding: 20px; margin-bottom: 20px;">
                            <div style="margin-bottom: 15px;">
                                <strong style="color: #374151;">📱 Kenapa Telegram?</strong>
                                <ul style="margin: 10px 0 0 20px; color: #6b7280; font-size: 14px; line-height: 1.8;">
                                    <li>✅ Gratis (tidak ada biaya per pesan)</li>
                                    <li>✅ Setup cepat (tidak perlu approval)</li>
                                    <li>✅ Semua fitur WhatsApp tersedia</li>
                                    <li>✅ UI lebih baik (inline keyboards)</li>
                                </ul>
                            </div>
                        </div>
                        
                        <form method="POST" style="background: white; border: 1px solid #e5e7eb; border-radius: 12px; padding: 25px;">
                            <div style="margin-bottom: 20px;">
                                <label style="display: flex; align-items: center; gap: 10px; cursor: pointer;">
                                    <input type="checkbox" name="telegram_enabled" id="telegram_enabled" style="width: 20px; height: 20px;">
                                    <span style="font-weight: 600; color: #374151;">Enable Telegram Bot</span>
                                </label>
                                <p style="margin: 8px 0 0 30px; font-size: 13px; color: #6b7280;">Aktifkan bot Telegram untuk menerima pesan dari user</p>
                            </div>
                            
                            <div style="margin-bottom: 20px;">
                                <label style="display: block; margin-bottom: 8px; font-weight: 500; color: #374151;">
                                    Bot Token <span style="color: #ef4444;">*</span>
                                </label>
                                <input type="text" name="telegram_bot_token" class="form-control" placeholder="1234567890:ABCdefGHIjklMNOpqrsTUVwxyz" style="width: 100%; padding: 12px; border: 1px solid #d1d5db; border-radius: 8px; font-size: 14px; font-family: 'Courier New', monospace;">
                                <p style="margin: 8px 0 0 0; font-size: 13px; color: #6b7280;">
                                    <i class="fas fa-info-circle"></i> Dapatkan dari <strong>@BotFather</strong> di Telegram (kirim /newbot)
                                </p>
                            </div>
                            
                            <div style="margin-bottom: 20px;">
                                <label style="display: block; margin-bottom: 8px; font-weight: 500; color: #374151;">
                                    Admin Chat IDs
                                </label>
                                <input type="text" name="telegram_admin_chat_ids" class="form-control" placeholder="123456789, 987654321" style="width: 100%; padding: 12px; border: 1px solid #d1d5db; border-radius: 8px; font-size: 14px;">
                                <p style="margin: 8px 0 0 0; font-size: 13px; color: #6b7280;">
                                    <i class="fas fa-info-circle"></i> Dapatkan Chat ID dari <strong>@userinfobot</strong> (pisahkan dengan koma jika lebih dari 1)
                                </p>
                            </div>
                            
                            <div style="margin-bottom: 20px;">
                                <label style="display: flex; align-items: center; gap: 10px; cursor: pointer;">
                                    <input type="checkbox" name="telegram_webhook_mode" id="telegram_webhook_mode" checked style="width: 20px; height: 20px;">
                                    <span style="font-weight: 500; color: #374151;">Use Webhook Mode</span>
                                </label>
                                <p style="margin: 8px 0 0 30px; font-size: 13px; color: #6b7280;">
                                    Webhook (butuh HTTPS) lebih efisien. Uncheck jika server belum ada SSL.
                                </p>
                            </div>
                            
                            <div style="background: #fffbeb; border: 1px solid #fde68a; border-radius: 8px; padding: 15px; margin-bottom: 20px;">
                                <strong style="color: #92400e; display: block; margin-bottom: 8px;">
                                    <i class="fas fa-lightbulb"></i> Langkah Setup:
                                </strong>
                                <ol style="margin: 0; padding-left: 20px; color: #92400e; font-size: 13px; line-height: 1.8;">
                                    <li>Buka Telegram → Cari <strong>@BotFather</strong></li>
                                    <li>Kirim <code>/newbot</code> dan ikuti instruksi</li>
                                    <li>Salin <strong>Bot Token</strong> yang diberikan</li>
                                    <li>Paste token di form ini → Klik Save</li>
                                    <li>Cari bot Anda di Telegram → Kirim <code>/start</code></li>
                                    <li>Setup webhook di <code>settings/telegram_settings.php</code></li>
                                </ol>
                            </div>
                            
                            <button type="submit" name="save_telegram_config" class="btn btn-primary" style="width: 100%; padding: 14px; font-size: 16px; background: #4f46e5; color: white; border: none; border-radius: 8px; font-weight: 600; cursor: pointer;">
                                <i class="fas fa-save"></i> Save Telegram Configuration
                            </button>
                            
                            <p style="margin-top: 15px; font-size: 13px; color: #6b7280; text-align: center;">
                                <i class="fas fa-info-circle"></i> Anda bisa skip ini dan konfigurasi nanti di <strong>settings/telegram_settings.php</strong>
                            </p>
                        </form>
                    </div>
                    
                    <div style="text-align: center; margin-top: 30px;">

                        <a href="index.php" class="btn btn-success btn-block" style="padding: 16px; font-size: 18px;">
                            <i class="fas fa-check-double"></i> Selesai & Buka Aplikasi
                        </a>
                        <div class="alert alert-warning" style="margin-top: 20px;">
                            <i class="fas fa-trash-alt"></i>
                            <div><strong>PENTING:</strong> Demi keamanan, silakan hapus file <code>install.php</code> ini sekarang.</div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
    </div>
</div>

<div class="footer" style="text-align: center; margin-top: 30px; padding-bottom: 30px; color: #6b7280; font-size: 14px;">
    <p style="margin-bottom: 5px;">MikhMon-Agent Mod by <strong>ALIJAYA-NET</strong></p>
    <p>Support & Donate : <a href="https://wa.me/6281947215703" target="_blank" style="color: var(--primary); text-decoration: none; font-weight: 600;">081947215703</a></p>
</div>

</body>
</html>
